### ISSUE TITLE
 Bug: 0 FLT

### ISSUE THREAD

**Issue by 1997roylee** [fluencelabs/dev-rewards#26]
Error: invalid BigNumber value (argument="value", value=[{"type":"BigNumber","hex":"0x010f0cf064dd59200000"}], code=INVALID_ARGUMENT, version=bignumber/5.7.0)
    at _r.makeError (index.ts:269:28)
    at _r.throwError (index.ts:281:20)
    at _r.throwArgumentError (index.ts:285:21)
    at di.from (bignumber.ts:289:23)
    at nI (fixednumber.ts:47:23)
    at lI (index.ts:69:12)
    at distributor.js:51:30

**Comment by akim-bow** [comment]
Thanks! Should be fixed by now.
