### ISSUE TITLE
Can not claim token

### ISSUE THREAD

**Issue by huynguyennovem** [fluencelabs/dev-rewards#31]
Thanks for the program!

But I got an issue. After I had the proof string, I pasted it to proof page but there are only two alert dialogs:

![image](https://github.com/fluencelabs/dev-rewards/assets/29337364/ffd0a844-575c-480d-b35e-bd8747f5017c)

```
Cannot confirm that tokens are not claimed yet.
```

```
Proof has invalid format
```

How to solve this?

**Comment by huynguyennovem** [comment]
I open the console to observe issue:

- On Chrome browser, I see it's stucked at `claiming with ...`
- On Edge browser, there are two alert dialogs as above, and I see the error from the console:

```console
governance.js:126 
 Error: unknown account #0 (operation="getAddress", code=UNSUPPORTED_OPERATION, version=providers/5.7.2)
    at _r.makeError (index.ts:269:28)
    at _r.throwError (index.ts:281:20)
    at json-rpc-provider.ts:204:24
    at async Promise.all (index 0)
```

**Comment by daizong** [comment]
the same problem.

**Comment by hongda3141** [comment]
> I connect wallet again to solve it.

Ditto

**Comment by huynguyennovem** [comment]
>I connect wallet again to solve it.

Can you please be more specific? I use MetaMask, it only provides the wallet address to the Proof as I can see.

**Comment by hongda3141** [comment]
> > I connect wallet again to solve it.
> 
> Can you please be more specific? I use MetaMask, it only provides the wallet address to the Proof as I can see.

I just refresh the chrome browser so I could reconnect the wallet, and I added all the code that program generated to the box.

**Comment by huynguyennovem** [comment]
>I just refresh the chrome browser so I could reconnect the wallet, and I added all the code that program generated to the box.

Thanks, but still doesn't work for me

**Comment by akim-bow** [comment]
Hi! You can try both python script and bash script to generate signature. Also try to use Metamask only, as it's best supported option.

**Comment by huynguyennovem** [comment]
> Hi! You can try both python script and bash script to generate signature. Also try to use Metamask only, as it's best supported option.

I tried Python, it generated the same string and had the same issue as Docker above

**Comment by akim-bow** [comment]
Any errors in browser console?

**Comment by huynguyennovem** [comment]
> Any errors in browser console?

Yes. I already shared it above: https://github.com/fluencelabs/dev-rewards/issues/31#issuecomment-1973752768. Will share here again. The error also appears on Chrome browser.

```console
governance.js:126 Error: unknown account #0 (operation="getAddress", code=UNSUPPORTED_OPERATION, version=providers/5.7.2)
    at _r.makeError (index.ts:269:28)
    at _r.throwError (index.ts:281:20)
    at json-rpc-provider.ts:204:24
    at async Promise.all (index 0)
(anonymous) @ governance.js:126
await in (anonymous) (async)
(anonymous) @ redux-thunk.mjs:5
onSubmit @ proof-page.js:66
je @ react-dom.production.min.js:54
ze @ react-dom.production.min.js:54
(anonymous) @ react-dom.production.min.js:55
Br @ react-dom.production.min.js:105
Dr @ react-dom.production.min.js:106
(anonymous) @ react-dom.production.min.js:117
ul @ react-dom.production.min.js:274
Te @ react-dom.production.min.js:52
Wr @ react-dom.production.min.js:109
Zt @ react-dom.production.min.js:74
Vt @ react-dom.production.min.js:73
Show less
proof-page.js:151 TypeError: Cannot read properties of undefined (reading 'message')
    at onSubmit (proof-page.js:140:37)
```

**Comment by akim-bow** [comment]
I see, more logs are always useful to debug.
Please try the following:
- clear browser cache, site cookies and localstorage
- go to the page, put your GitHub nickname.
- on the wallet connection step - connect your wallet as regular, via MetaMask. Make sure that wallet is actually connected, e.g., it persists between page restarts, you see the address on submit proof page near the title.
- After that, do the claiming.
Please report if one of these step fails.

**Comment by Polkaverse** [comment]
@huynguyennovem do we need to pay fees to claim the rewards?
