### ISSUE TITLE
Malformed SSH identity despite identity being validated by ssh-keygen

### ISSUE THREAD

**Issue by PoisonPhang** [fluencelabs/dev-rewards#50]
Not sure why my ssh key is not parsable given running `ssh-keygen -lf ~/.ssh/id_rsa` has no trouble parsing the key.

Any help would be great, thanks.

Here is the error returned while trying to generate the proof with Docker.

```
Your ssh keys in ~/.ssh:
/root/.ssh/id_rsa

Now the script needs your ssh key to generate proof. Please, enter path for github SSH key:
/root/.ssh/id_rsa
Traceback (most recent call last):
  File "/claim/python/proof.py", line 161, in <module>
    main()
  File "/claim/python/proof.py", line 146, in main
    tempETHAccount = decrypt_temp_eth_account(
  File "/claim/python/proof.py", line 117, in decrypt_temp_eth_account
    raise OSError(result.stderr)
OSError: b'age: error: reading "/root/.ssh/id_rsa": malformed SSH identity in "/root/.ssh/id_rsa": ssh: parse error in message type 0\nage: report unexpected or unhelpful errors at https://filippo.io/age/report\n'
```

**Comment by akim-bow** [comment]
What about other methods, e.g., python?

**Comment by PoisonPhang** [comment]
Trying this again, on a different computer with the same key, seemed to work. Will close.
