### ISSUE TITLE
I use the python to run the scripts,but i encounter  the issue

### ISSUE THREAD

**Issue by beterhub** [fluencelabs/dev-rewards#89]
the issue is blow:
PS F:\github\fluence\dev-rewards-main> & C:/software/conda/envs/tokening/python.exe f:/github/fluence/dev-rewards-main/python/proof.py
Traceback (most recent call last):
  File "f:/github/fluence/dev-rewards-main/python/proof.py", line 11, in <module>
    from helpers.common import Metadata
  File "f:\github\fluence\dev-rewards-main\python\helpers\common.py", line 7, in <module>
    class Metadata:
  File "f:\github\fluence\dev-rewards-main\python\helpers\common.py", line 9, in Metadata
    addresses: list[str]
TypeError: 'type' object is not subscriptable

**Comment by akim-bow** [comment]
Make sure you have Python version 3.9 and later
